@startuml
'https://plantuml.com/class-diagram

class FireBaseFirestore
{
    +CollectionReference collection(String)
    +DocumentReference document(String)
}

package Ingredient #DDD
{
    class Ingredient
    {
        -String description
        -Date bestBeforeDate
        -String location
        -int count
        -String unit
        -String category

        -String formattedBestBeforeDate()
    }
    package IngredientFragment #AFA
    {
        class ActivityResultLauncher
        {
            +void onActivityResult(ActivityResult)
        }
        class CalendarActivity
        {
            - String date
            * void onCreate(Bundle savedInstanceState)
            - void done()
        }
        class IngredientFragment
        {
            -EditText ingredientDescription;
            -EditText ingredientLocation;
            -EditText ingredientBestBeforeDate;
            -EditText ingredientCount;
            -EditText ingredientUnit;
            -EditText ingredientCategory;
            -OnFragmentInteractionListener listener;
            -FireBaseFirestore db
            -ActivityResultLauncher<Intent> calendarActivity

            - Date calendarDate
            - {static} String triggerFlag

            + {static} void onAttach(@NonNull Context)
            + {static} IngredientFragment NewInstance(Ingredient)
            + Dialog onCreateDialog(@Nullable Bundle)
            - void setDate(String)
            + int parseCount(String count)
            - boolean emptyStringCheck(String, String, String, String, String, String)

            + {static}void addIngredientDB(Ingredient, CollectionReference)
            + {static}void delIngredientDB(String, CollectionReference)
            + {static}void editIngredientDB(String, Ingredient, CollectionReference)
        }
    }
    package IngredientActivity #AFA
    {
        interface Ingredient.OnFragmentInteractionListener
        {
            +void onOkPressed(Ingredient newIngredient);
            +void onOkPressedEdit(Ingredient newIngredient);
        }
        class CustomIngredientArrayAdapter
        {
            - ArrayList<Ingredient> ingredients
            - Context context
            - FireBaseFirestore db

            + View getView(int, @Nullable View, @NonNull ViewGroup)
        }
        class IngredientActivity implements Ingredient.OnFragmentInteractionListener
        {
            -ListView ingredientList
            -ArrayAdapter<Ingredient> ingredientAdapter
            -ArrayList<Ingredient> dataList
            -int selected
            -FireBaseFirestore db
            -final String[] sortValues = { "description", "best before date", "location", "category" }

            *void onCreate(Bundle)
            +void onOkPressed(Ingredient)
            +void onOkPressedEdit(Ingredient)
        }

    }
    Serializable ()- Ingredient : Implements

    IngredientActivity  o--   "0..*" Ingredient
    IngredientFragment  o--   "0..*" Ingredient
    CustomIngredientArrayAdapter --o IngredientActivity

    FireBaseFirestore --o "0..*" IngredientActivity
    FireBaseFirestore --o "0..*" CustomIngredientArrayAdapter
    FireBaseFirestore --o "0..*" IngredientFragment

    Ingredient.OnFragmentInteractionListener <-* IngredientFragment
    IngredientActivity <-> IngredientFragment
    CalendarActivity <-> ActivityResultLauncher
    ActivityResultLauncher <--o "1" IngredientFragment
}

class CameraActivity{}

package Recipe #DDD
{
    class Recipe
    {
        -String title
        -int prep_time
        -int servings
        -String comments
        -String category
        -String picture
        -ArrayList<Ingredient> ingredientList;

        +void addIngredient(Ingredient)
        +void removeIngredient(Ingredient)
    }
    package RecipeFragment #DAA
    {
        class Recipe.ActivityResultLauncher
        {
            +void onActivityResult(ActivityResult)
        }

        interface Recipe.OnFragmentInteractionListener
        {
            +void onOkPressed(Ingredient newIngredient);
            +void onOkPressedEdit(Ingredient newIngredient);
        }
        class RecipeFragment
        {
            -ImageView recipeImage
            -EditText recipeTitle
            -EditText recipePrepareTime
            -EditText recipeServings
            -EditText recipeCategory
            -EditText recipeComments
            -Uri imageURI
            -OnFragmentInteractionListener listener;
            -FireBaseFirestore db
            -ActivityResultLauncher<Intent> cameraActivity
            -ActivityResultLauncher<Intent> ingredientActivity

            + {static} void onAttach(@NonNull Context)
            + {static} RecipeFragment NewInstance(Recipe)
            + Dialog onCreateDialog(@Nullable Bundle)
            - boolean emptyStringCheck(String, String, String, String, String)

            + {static} void delRecipeDB(Recipe, CollectionReference)
            + {static} void addRecipeDB(Recipe, CollectionReference)
            + {static} void editRecipeDB(Recipe, Recipe, CollectionReference)

            - int parsePrepTime(String prepTime)
            - int parseServing(String serving)
            - String bitmapToString(Bitmap picture)
        }
        class RecipeIngredientsActivity implements Recipe.OnFragmentInteractionListener
        {
            -ListView ingredientList;
            -ArrayAdapter<Ingredient> ingredientAdapter;
            -ArrayList<Ingredient> dataList;
            -int selected;

            *void onResume()
            *void onCreate(Bundle savedInstanceState)
            +void onOkPressed(Ingredient newIngredient)
            +void onOkPressedEdit(Ingredient ingredient)
            +void Done()
        }
    }
    package RecipeActivity #DAA
    {
        class RecipeActivity implements Recipe.OnFragmentInteractionListener
        {
            -ListView recipeListView
            -ArrayAdapter<Recipe> recipeAdapter
            -ArrayList<Recipe> recipeList
            -int selected
            -String[] sortValues = { "title", "prep time", "# of servings", "category" }

            *void onCreate(Bundle)
            +void onOkPressedRecipe(Recipe)
            +void onOkPressedEditRecipe(Recipe)
        }
        class CustomRecipeArrayAdapter
        {
            - ArrayList<Recipe> recipes
            - Context context
            - FireBaseFirestore db

            + View getView(int, @Nullable View, @NonNull ViewGroup)
        }
    }
    Serializable ()-- Recipe : Implements

    Ingredient "0..*" -o "0..*" Recipe

    RecipeActivity o- "0..*" Recipe
    CustomRecipeArrayAdapter "1" --o RecipeActivity
    Recipe.OnFragmentInteractionListener <-* RecipeFragment

    FireBaseFirestore --o RecipeActivity
    FireBaseFirestore --o RecipeFragment
    FireBaseFirestore --o CustomRecipeArrayAdapter

    RecipeActivity <--> RecipeFragment
    RecipeFragment "2" o--> Recipe.ActivityResultLauncher
    Recipe.ActivityResultLauncher <--> CameraActivity
    Recipe.ActivityResultLauncher <-> RecipeIngredientsActivity
}
package MealPlan #DDD
{
    class Meal
    {
        -String mealName;
        -String mealType;
        -Date date;
        -int scale;
        +String getFormattedDate();
    }
    package MealPlanScaleFragment #DAF
    {
        class MealPlanScaleFragment
        {
            -MealPlanScaleFragment.OnFragmentInteractionListener listener;
            -FirebaseFirestore db;
            -EditText mealScale_ET;
            +void onAttach(@NonNull Context context)
            +void {static} MealPlanScaleFragment newInstance(Meal meal)
            +Dialog onCreateDialog(@Nullable Bundle savedInstanceState)
        }
        interface MealPlanScaleFragment.OnFragmentInteractionListener
        {
            -void onOkPressed(Meal newMeal);
            -void onOkEditPressed(Meal newMeal);
        }
    }
    package MealPlanFragment #DAF
        {
        class MealPlanFragment.ActivityResultLauncher
        {
            +void onActivityResult(ActivityResult)
        }
        class MealPlanFragment.CalendarActivity
        {
            - String date
            * void onCreate(Bundle savedInstanceState)
            - void done()
        }
        class MealPlanFragment
        {
            -FirebaseFirestore db;
            -MealPlanScaleFragment.OnFragmentInteractionListener listener;
            -ArrayAdapter<Ingredient> ingredientAdapter;
            -ArrayList<Ingredient> ingredientdataList;
            -ArrayAdapter<Recipe> recipeAdapter;
            -ArrayList<Recipe> recipedataList;
            -Date calendarDate;
            -ListView ItemList;
            -Ingredient selectedIngredient;
            -Recipe selectedRecipe;
            -String type;
            -ActivityResultLauncher<Intent> calendarActivity;

            +void {static} addMealRecipeDB(Meal, Recipe, CollectionReference);
            +void {static} delMealRecipeDB(Recipe, CollectionReference);
            +void {static} editMealRecipeDB(Recipe, Meal, Recipe, CollectionReference);
            +void {static} addMealIngredientDB(Meal, Ingredient, CollectionReference);
            +void {static} delMealIngredientDB(String, String, CollectionReference);
            +void {static} editMealIngredientDB(String, String, Meal, Ingredient, CollectionReference);
            +void onAttach(@NonNull Context);
            +void {static} MealPlanFragment newInstance(String);
            +View onCreateView(@NonNull LayoutInflater, @Nullable ViewGroup, @Nullable Bundle);
            -void setDate(String);
        }
    }
    package MealPlanActivity #DAF
    {
        class CustomMealPlanArrayAdapter
        {
            -ArrayList<Meal> meals;
            -Context context;
            -FirebaseFirestore db;
            +View getView(int, @Nullable View, @NonNull ViewGroup);
        }
        class MealPlanActivity implements MealPlanScaleFragment.OnFragmentInteractionListener
        {
            -ListView mealPlanListView;
            -ArrayAdapter<Meal> mealplanAdapter;
            -ArrayList<Meal> mealplanList;
            -FirebaseFirestore db;
            -int selected;
            -FloatingActionButton addMealPlan, addmIngredientButton, addmRecipeButton;
            -TextView addmIngredientText, addmRecipeText;
            -boolean isAllFabsVisible;

            *void onCreate(Bundle savedInstanceState);
            +void onOkPressed(Meal newMeal);
            +void onOkEditPressed(Meal newMeal);
        }
    }
    Serializable ()- Meal : Implements

    MealPlanFragment o--> "1" MealPlanFragment.ActivityResultLauncher
    MealPlanFragment.ActivityResultLauncher <--> MealPlanFragment.CalendarActivity
    Meal "0..*" --o MealPlanActivity
    Meal "0..*" --o MealPlanFragment

    MealPlanActivity <-> MealPlanFragment
    MealPlanActivity o-- CustomMealPlanArrayAdapter
    MealPlanScaleFragment <-> MealPlanActivity
    MealPlanScaleFragment *--> MealPlanScaleFragment.OnFragmentInteractionListener

    FireBaseFirestore ---o MealPlanFragment
    FireBaseFirestore ---o MealPlanActivity
    FireBaseFirestore ---o MealPlanScaleFragment
}
package ShoppingList #DDD
{
    class ShoppingItem extends Ingredient
    {
        -boolean Checked = false
        -int oldcount
    }
    package ShoppingListFragment #DFF
    {
        interface ShoppingListFragment.OnFragmentInteractionListener
        {
            +void onOkPressedEdit(ShoppingItem newItem)
        }
        class ShoppingItemFragment
        {
            -EditText itemDescription
            -EditText itemCount
            -EditText itemUnit
            -EditText itemLocation
            -TextView itemBestBeforeDate
            -Date calendarDate
            -EditText itemCategory
            -OnFragmentInteractionListener listener
            -FirebaseFirestore db
            -ActivityResultLauncher<Intent> calendarActivity

            -void setDate(String date)
            -int parseCount(String count)
            +void onAttach(@NonNull Context context)
            +{static}void editShoppingItemDB(String oldItem, Ingredient newItem, CollectionReference IngredientCollection)
            +{static} ShoppingItemFragment newInstance(ShoppingItem item)
            +Dialog onCreateDialog(@Nullable Bundle savedInstanceState)
            +boolean emptyStringCheck(String description, String location, String count, String unit, String category)

        }
    }
    package ShoppingListActivity #DFF
    {
        class CustomShoppingItemArrayAdapter
        {
            -ArrayList<ShoppingItem> items
            -Context context
            -FirebaseFirestore db

            +CustomShoppingItemArrayAdapter(Context context, ArrayList<ShoppingItem> items)
            +View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent)
        }
        class ShoppingListActivity implements ShoppingListFragment.OnFragmentInteractionListener
        {
                -ListView shoppingList
                -ArrayAdapter<ShoppingItem> shoppingAdapter
                -ArrayList<ShoppingItem> dataList
                -ArrayList<ShoppingItem> tempList
                -int selected
                -FirebaseFirestore db
                -String[] sortValues = { "description", "category" }

                *void onCreate(Bundle savedInstanceState)
                +void onOkPressedEdit(ShoppingItem item)
                +void additem(ShoppingItem item)
                +void additemCheck(ShoppingItem item)
        }
    }
    ShoppingListActivity o-- "1" CustomShoppingItemArrayAdapter
    ShoppingItemFragment <--> ShoppingListActivity

    ShoppingItemFragment *--> ShoppingListFragment.OnFragmentInteractionListener
    ShoppingItem "0..*" -o ShoppingItemFragment
    ShoppingItem "0..*" -o ShoppingListActivity

    FireBaseFirestore --o ShoppingListActivity
    FireBaseFirestore --o ShoppingItemFragment
    FireBaseFirestore --o CustomShoppingItemArrayAdapter
}

IngredientActivity <-> MealPlanActivity
IngredientActivity <-> RecipeActivity
IngredientActivity <-> ShoppingListActivity

MealPlanActivity <-> RecipeActivity
MealPlanActivity <-> ShoppingListActivity

Recipe <-> ShoppingListActivity



@enduml