@startuml
'https://plantuml.com/class-diagram

class Ingredient
{
    -String description
    -Date bestBeforeDate
    -String location
    -int count
    -String unit
    -String category

    -String formattedBestBeforeDate()
}
Serializable ()-- Ingredient : Implements

class FireBaseFirestore
{
    +CollectionReference collection(String)

}

package Recipe
{
    class Recipe
    {
        -String title
        -int prep_time
        -int servings
        -String comments
        -String category
        -String picture

        +void addIngredient(Ingredient)
        +void removeIngredient(Ingredient)
    }
    package RecipeFragment
    {
        class ActivityResultLauncher
        {
            +void onActivityResult(ActivityResult)
        }
        class CalendarActivity
        {
            - String date
            * void onCreate(Bundle savedInstanceState)
            - void done()
        }
        interface OnFragmentInteractionListener
        {
            +void onOkPressed(Ingredient newIngredient);
            +void onOkPressedEdit(Ingredient newIngredient);
        }
        class RecipeFragment
        {
            -ImageView recipeImage
            -EditText recipeTitle
            -EditText recipePrepareTime
            -EditText recipeServings
            -EditText recipeCategory
            -EditText recipeComments
            -Uri imageURI
            -OnFragmentInteractionListener listener;
            -FireBaseFirestore db
            -ActivityResultLauncher<Intent> cameraActivity
            -ActivityResultLauncher<Intent> ingredientActivity

            + {static} void onAttach(@NonNull Context)
            + {static} RecipeFragment NewInstance(Recipe)
            + Dialog onCreateDialog(@Nullable Bundle)
            - boolean emptyStringCheck(String, String, String, String, String)

            + {static} void delRecipeDB(Recipe, CollectionReference)
            + {static} void addRecipeDB(Recipe, CollectionReference)
            + {static} void editRecipeDB(Recipe, Recipe, CollectionReference)

            - int parsePrepTime(String prepTime)
            - int parseServing(String serving)
            - String bitmapToString(Bitmap picture)
        }
        class RecipeIngredientsActivity implements OnFragmentInteractionListener
        {
            -ListView ingredientList;
            -ArrayAdapter<Ingredient> ingredientAdapter;
            -ArrayList<Ingredient> dataList;
            -int selected;

            *void onResume()
            *void onCreate(Bundle savedInstanceState)
            +void onOkPressed(Ingredient newIngredient)
            +void onOkPressedEdit(Ingredient ingredient)
            +void Done()
        }
    }
    package RecipeActivity
    {
        class RecipeActivity implements OnFragmentInteractionListener
        {
            -ListView recipeListView
            -ArrayAdapter<Recipe> recipeAdapter
            -ArrayList<Recipe> recipeList
            -int selected
            -String[] sortValues = { "title", "prep time", "# of servings", "category" }

            *void onCreate(Bundle)
            +void onOkPressedRecipe(Recipe)
            +void onOkPressedEditRecipe(Recipe)
        }
        class CustomRecipeArrayAdapter
        {
            - ArrayList<Recipe> recipes
            - Context context
            - FireBaseFirestore db

            + View getView(int, @Nullable View, @NonNull ViewGroup)
        }
    }
    Serializable ()-- Recipe : Implements

    Ingredient "0..*" -o "0..*" Recipe

    RecipeActivity *-> "0..*" Recipe
    CustomRecipeArrayAdapter --o RecipeActivity
    FireBaseFirestore --o "0..*" RecipeActivity

    OnFragmentInteractionListener <-* RecipeFragment
    FireBaseFirestore --o "0..*" RecipeFragment
    FireBaseFirestore --o "0..*" CustomRecipeArrayAdapter

    RecipeActivity <--> RecipeFragment
    RecipeFragment --> ActivityResultLauncher
    ActivityResultLauncher -> CalendarActivity
    ActivityResultLauncher -> RecipeIngredientsActivity
}


@enduml